name: CI

on:
  push:
    branches:
      - 'main'

permissions:
  contents: read
  packages: write

jobs:
  devcontainer:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: |
          set -e

          FOLDER_WITH_DOT_DEVCONTAINER="devcontainer-sam-terraform"
          IMAGE_NAME="devcontainer-sam-terraform"
          IMAGE_REPOSITORY="$(echo "ghcr.io/${{ github.repository_owner }}/${IMAGE_NAME}" | tr '[:upper:]' '[:lower:]')"

          # [Optional] Enable buildkit, set output to plain text for logging
          export DOCKER_BUILDKIT=1
          export BUILDKIT_PROGRESS=plain

          # Build the image
          npm run build -- --no-cache --image-name "${IMAGE_REPOSITORY}" "${FOLDER_WITH_DOT_DEVCONTAINER}"

          # Push the image
          echo "${{ github.token }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
          docker push "${IMAGE_REPOSITORY}"
